/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProspeccaoRouteImport } from './routes/_authenticated/prospeccao'
import { Route as AuthenticatedInteligenciaIndexRouteImport } from './routes/_authenticated/inteligencia/index'
import { Route as AuthenticatedInteligenciaRelatorioRouteImport } from './routes/_authenticated/inteligencia/relatorio'
import { Route as AuthenticatedInteligenciaHistoricoRouteImport } from './routes/_authenticated/inteligencia/historico'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProspeccaoRoute = AuthenticatedProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInteligenciaIndexRoute =
  AuthenticatedInteligenciaIndexRouteImport.update({
    id: '/inteligencia/',
    path: '/inteligencia/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInteligenciaRelatorioRoute =
  AuthenticatedInteligenciaRelatorioRouteImport.update({
    id: '/inteligencia/relatorio',
    path: '/inteligencia/relatorio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInteligenciaHistoricoRoute =
  AuthenticatedInteligenciaHistoricoRouteImport.update({
    id: '/inteligencia/historico',
    path: '/inteligencia/historico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/inteligencia/historico': typeof AuthenticatedInteligenciaHistoricoRoute
  '/inteligencia/relatorio': typeof AuthenticatedInteligenciaRelatorioRoute
  '/inteligencia/': typeof AuthenticatedInteligenciaIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/': typeof AuthenticatedIndexRoute
  '/inteligencia/historico': typeof AuthenticatedInteligenciaHistoricoRoute
  '/inteligencia/relatorio': typeof AuthenticatedInteligenciaRelatorioRoute
  '/inteligencia': typeof AuthenticatedInteligenciaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/inteligencia/historico': typeof AuthenticatedInteligenciaHistoricoRoute
  '/_authenticated/inteligencia/relatorio': typeof AuthenticatedInteligenciaRelatorioRoute
  '/_authenticated/inteligencia/': typeof AuthenticatedInteligenciaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/prospeccao'
    | '/inteligencia/historico'
    | '/inteligencia/relatorio'
    | '/inteligencia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/prospeccao'
    | '/'
    | '/inteligencia/historico'
    | '/inteligencia/relatorio'
    | '/inteligencia'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/prospeccao'
    | '/_authenticated/'
    | '/_authenticated/inteligencia/historico'
    | '/_authenticated/inteligencia/relatorio'
    | '/_authenticated/inteligencia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospeccao': {
      id: '/_authenticated/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof AuthenticatedProspeccaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inteligencia/': {
      id: '/_authenticated/inteligencia/'
      path: '/inteligencia'
      fullPath: '/inteligencia/'
      preLoaderRoute: typeof AuthenticatedInteligenciaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inteligencia/relatorio': {
      id: '/_authenticated/inteligencia/relatorio'
      path: '/inteligencia/relatorio'
      fullPath: '/inteligencia/relatorio'
      preLoaderRoute: typeof AuthenticatedInteligenciaRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inteligencia/historico': {
      id: '/_authenticated/inteligencia/historico'
      path: '/inteligencia/historico'
      fullPath: '/inteligencia/historico'
      preLoaderRoute: typeof AuthenticatedInteligenciaHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProspeccaoRoute: typeof AuthenticatedProspeccaoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInteligenciaHistoricoRoute: typeof AuthenticatedInteligenciaHistoricoRoute
  AuthenticatedInteligenciaRelatorioRoute: typeof AuthenticatedInteligenciaRelatorioRoute
  AuthenticatedInteligenciaIndexRoute: typeof AuthenticatedInteligenciaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProspeccaoRoute: AuthenticatedProspeccaoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInteligenciaHistoricoRoute:
    AuthenticatedInteligenciaHistoricoRoute,
  AuthenticatedInteligenciaRelatorioRoute:
    AuthenticatedInteligenciaRelatorioRoute,
  AuthenticatedInteligenciaIndexRoute: AuthenticatedInteligenciaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
